#############################################################################
# Makefile for building: hartreefock_molecules
# Generated by qmake (2.01a) (Qt 4.8.4) on: man. apr. 14 10:53:37 2014
# Project:  hartreefock_molecules.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile hartreefock_molecules.pro
#############################################################################

####### Compiler, tools and options

CC            = mpicc
CXX           = mpicxx
DEFINES       = 
CFLAGS        = -pipe -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -DMPICH_IGNORE_CXX_SEEK -O2 -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -DMPICH_IGNORE_CXX_SEEK -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I.
LINK          = mpicxx
LFLAGS        = -pthread -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -lopen-rte -lopen-pal -Wl,--export-dynamic -lnsl -lutil -lm -ldl -Wl,-O1
LIBS          = $(SUBLIBS)   -llapack -lblas -lmpi 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		hartree_fock_solver.cpp \
		hartree_integrals.cpp \
		matrix_size_setter.cpp \
		fill_alpha.cpp \
		initializer.cpp \
		ccsd_memory_optimized.cpp 
OBJECTS       = main.o \
		hartree_fock_solver.o \
		hartree_integrals.o \
		matrix_size_setter.o \
		fill_alpha.o \
		initializer.o \
		ccsd_memory_optimized.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hartreefock_molecules.pro
QMAKE_TARGET  = hartreefock_molecules
DESTDIR       = 
TARGET        = hartreefock_molecules

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hartreefock_molecules.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile hartreefock_molecules.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile hartreefock_molecules.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hartreefock_molecules1.0.0 || $(MKDIR) .tmp/hartreefock_molecules1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hartreefock_molecules1.0.0/ && (cd `dirname .tmp/hartreefock_molecules1.0.0` && $(TAR) hartreefock_molecules1.0.0.tar hartreefock_molecules1.0.0 && $(COMPRESS) hartreefock_molecules1.0.0.tar) && $(MOVE) `dirname .tmp/hartreefock_molecules1.0.0`/hartreefock_molecules1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hartreefock_molecules1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp initializer.h \
		hartree_fock_solver.h \
		matrix_size_setter.h \
		fill_alpha.h \
		hartree_integrals.h \
		ccsd_memory_optimized.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

hartree_fock_solver.o: hartree_fock_solver.cpp hartree_fock_solver.h \
		matrix_size_setter.h \
		fill_alpha.h \
		hartree_integrals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hartree_fock_solver.o hartree_fock_solver.cpp

hartree_integrals.o: hartree_integrals.cpp hartree_integrals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hartree_integrals.o hartree_integrals.cpp

matrix_size_setter.o: matrix_size_setter.cpp matrix_size_setter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matrix_size_setter.o matrix_size_setter.cpp

fill_alpha.o: fill_alpha.cpp fill_alpha.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fill_alpha.o fill_alpha.cpp

initializer.o: initializer.cpp initializer.h \
		hartree_fock_solver.h \
		matrix_size_setter.h \
		fill_alpha.h \
		hartree_integrals.h \
		ccsd_memory_optimized.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o initializer.o initializer.cpp

ccsd_memory_optimized.o: ccsd_memory_optimized.cpp ccsd_memory_optimized.h \
		hartree_fock_solver.h \
		matrix_size_setter.h \
		fill_alpha.h \
		hartree_integrals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ccsd_memory_optimized.o ccsd_memory_optimized.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

